// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvrBJNQ1mlhshIdkKiILpRl5U2Q9grS1g',
    appId: '1:146231892644:web:873f7c6d08ddac4d27a431',
    messagingSenderId: '146231892644',
    projectId: 'sparepark-d7804',
    authDomain: 'sparepark-d7804.firebaseapp.com',
    storageBucket: 'sparepark-d7804.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEzUWLtd5AmJdm-rgoI982TAwimB1hRD4',
    appId: '1:146231892644:android:89529db118f8fa7727a431',
    messagingSenderId: '146231892644',
    projectId: 'sparepark-d7804',
    storageBucket: 'sparepark-d7804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCb902p75apUUJwz2q6Xb1k-K5c9weZRQ',
    appId: '1:146231892644:ios:a3a27962f67060af27a431',
    messagingSenderId: '146231892644',
    projectId: 'sparepark-d7804',
    storageBucket: 'sparepark-d7804.appspot.com',
    androidClientId: '146231892644-82704tgoi7mqhbkg57qevthqusd4uik8.apps.googleusercontent.com',
    iosClientId: '146231892644-pdvj4lui8u4igq19sq4qoo7fobj4af8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparepark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCb902p75apUUJwz2q6Xb1k-K5c9weZRQ',
    appId: '1:146231892644:ios:a3a27962f67060af27a431',
    messagingSenderId: '146231892644',
    projectId: 'sparepark-d7804',
    storageBucket: 'sparepark-d7804.appspot.com',
    androidClientId: '146231892644-82704tgoi7mqhbkg57qevthqusd4uik8.apps.googleusercontent.com',
    iosClientId: '146231892644-pdvj4lui8u4igq19sq4qoo7fobj4af8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparepark',
  );
}
